version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  
      MYSQL_DATABASE: devops
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - app-network

  backend-container:
    image: yussef123/yussoufarctic:latest #naoui-5actic5-g1-projet4
    container_name: backend-container
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devops
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:
networks:
  app-network:
    driver: bridge
